#hyperparameters
learning_rate: 0.001
num_epochs: 55
batch_size: 200 #400
weight_decay: 0 
class_weights: null # or specify the desired list of weights [1.0, 6.525]

#paths
train_set_path: 'Ship/dataset/sample'
test_set_path: '/output/test2_2023-09-08_16-45-54/stitching/final_results'
main_dict_path: 'Ship/dictionary/main_block_dict.json'
unit_dict_path: 'Ship/dictionary/unit_block_dict.json'
relationship_dict_path: 'Ship/dictionary/block_relationship.json'
mothership_dict_path: 'Ship/dictionary/mothership_dict.json'
result_dict_path: 'Ship/dictionary/result_dict'
checkpoint_path: 'Ship/param/efficientnetv2_s_bval.pt' #'Ship/param/efficientnetv2_s_bvalunitonly.pt' 
json_directory: 'Ship/dictionary'
snapshot_directory: 'Ship/dataset/img_source/snapshot/image'
jpg_directory: 'Ship/dataset/img_source/sample/train' #jpg카운트를 원하는 jpg파일 경로 입
results_directory: 'Ship/results'

#사용설명서
#run.py와 eval.py에 있는 config 경로를 가장 먼저 알맞게 수정해주세요.
#저희가 실험해본 결과 epoch은 40-50번 정도가 적당했습니다
#batch size 기준 64를 하면 약 60기가 정도의 메모리가 필요합니다

#mothership dict는 유일하게 자동화 되어있지 않은 dict이니 새로운 배가 추가 될때 마다 수정울 해주셔야 합니다
#만약에 엑셀 파일로 호선이 정리가 되면 [  ="""" & $호선 & """:" & """" & $대표호선 & """, "  ] 엑셀 함수를 쓰면 엑셀에서 이 dict에서 쓰는 형식으로 바꿀수 있습니다
#이것에 대한 예시 엑셀은 본 폴더 안 예시 폴더 안에 넣어두었습니다

#Others 폴더에 있는 파일들은 학습에는 필요 없지만 저희가 데이터셋을 준비할때 필요했던 코드들입니다
#만약에 데이터셋이 알려주신대로 준비가 되었다면 쓰실 필요는 없습니다
#compcnf는 3d snapshot train 데이터와 실사 test 데이터를 비교해 실사데이터에는 있지만 3d snapshot 데이터에는 없는 배들을 찾아서 실사 데이터를 삭제 해주는 코드입니다
#delete0는 메인블록의 끝에 '0'이 있는지 확인하고 없으면 삭제해주는 코드입니다
#현재 쓰는 efficientnet 코드는 소스 코드에 바로 수정을 해서 본 파일에 있는 efficientnet기존코드덮어쓰기.py로 efficientnet.py를 복사+붙혀넣기 하셔서 덮어쓰셔야 합니다
